# title: Intro to Computer Vision
# name: Intro to Computer Vision
# description: The course page for ARTTECH-3039, Intro to Computer Vision.
# forum: https://ats.community/c/courses/arttech-3039-spring-2018
name: Intro to Computer Vision
number: ARTTECH-3039
description: >
  Computer vision allows machines to see and understand their environment. This
  course will equip students with the practical skills and critical theory
  needed to both employ and critically engage these techniques. Real-time body
  tracking, facial recognition and gesture analysis using RGB+D and LiDAR
  sensors, artificial intelligence and machine learning will be emphasized.
  Students will explore and critique contemporary applications ranging from
  automated mass surveillance to interactive installations. A final project will
  build on in-class workshops, technical exercises, critical readings and
  discussions.
forum: https://saic.instructure.com/courses/2535662/discussion_topics
semester: Summer
year: 2019
meetings:
  - Daily 9am-4:30pm
locations:
  - MacLean 401
sites:
  - name: Canvas
    url: https://saic.instructure.com/courses/2535662
  - name: General Code Discussion (Public)
    url: https://ats.community/
    comments: Post your questions in the appropriate category.
  - name: Class Website
    url: http://saic-ats.github.io/ARTTECH-3039/
  - name: Course Repository (code examples, etc)
    url: https://github.com/SAIC-ATS/ARTTECH-3039/
  - name: Course Assignments
    url: https://github.com/SAIC-ARTTECH-3039-5039
  - name: Course openFrameworks Addon
    url: https://github.com/SAIC-ATS/ofxARTTECH-3039

people:
  - name: Christopher Baker
    role: Instructor
    gravatar: 8f6ac7bc0f5c26b87269d442d5339206
    email: info@christopherbaker.net
    web: https://new.christopherbaker.net
    twitter: bakercp
    github: bakercp
    bio: >
      [Christopher Baker](https://new.christopherbaker.net) is an artist whose work
      engages the rich collection of social, technological and ideological networks
      present in the urban landscape. He creates artifacts and situations that
      reveal and generate relationships within and between these networks.
      Christopher’s work has been presented worldwide and he contributes to the open
      source community at [http://github.com/bakercp](http://github.com/bakercp).

#### JEKYLL ####

baseurl: /ARTTECH-3039
url: https://saic-ats.github.io/ARTTECH-3039

timezone: America/Chicago

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

markdown: kramdown
highlighter: rouge
permalink: pretty

# jekyll-SEO
# More: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
google_site_verification: hO8fb6wgSNVw6C5qMR4ehv-IkEJwBbBguiWxmcwcVxQ

# Custom Data
google_analytics: UA-105746846-4

# Collections
collections:
  assignments:
    output: true
    name: Assignments
  notes:
    output: true
    name: Notes
  resources:
    output: true
    name: Resources
  sessions:
    output: true
    name: Sessions

  # projects:
  #   output: true
  #   name: Projects

  # Session_00:
  #   output: true
  #   name: Session 00

# Default Values
defaults:
  - scope:
      path: ""
    values:
      author: bakercp
  - scope:
      path: ""
      type: sessions
    values:
      layout: session
  - scope:
      path: ""
      type: assignments
    values:
      layout: assignment

assets:
  css:
    - name: FontAwesome
      href: https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
      # integrity: sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN
      crossorigin: anonymous

    # - name: Bootstrap
    #   href: https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css
    #   integrity: sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm
    #   crossorigin: anonymous

    - name: Bootstrap Material Design
      href: https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css
      # integrity: sha384-R80DC0KVBO4GSTw+wZ5x2zn2pu4POSErBkf8/fSFhPXHxvHJydT0CSgAP2Yo2r4I
      crossorigin: anonymous

  js:
    - name: jQuery
      src: https://code.jquery.com/jquery-3.2.1.slim.min.js
      integrity: sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN
      crossorigin: anonymous

    # - name: Popper
    #   src: https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js
    #   integrity: sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q
    #   crossorigin: anonymous

    - name: Popper
      src: https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js
      integrity: sha256-/GXjBGBWRx8/y1Be190w3hrUOFXNs9qPhthi0tbNnG8=
      crossorigin: anonymous

    - name: Bootstrap Material Design
      src: https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js
      integrity: sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9
      crossorigin: anonymous

    # - name: Bootstrap
    #   src: https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js
    #   integrity: sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl
    #   crossorigin: anonymous

    - name: Moment.js
      src: https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js
      integrity: sha256-ABVkpwb9K9PxubvRrHMkk6wmWcIHUE9eBxNZLXYQ84k=
      crossorigin: anonymous

    - name: MathJax
      src: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
      integrity: sha384-ekJxthwrl3ID8DzHP2myRUdIPhTdEgNJ1xKhDsMKDT3+kBlZ4Zwk5zH960SnLZR8
      crossorigin: anonymous
