# title: Intro to Computer Vision
# name: Intro to Computer Vision
# description: The course page for ARTTECH-3039, Intro to Computer Vision.
# forum: https://ats.community/c/courses/arttech-3039-spring-2018
name: Intro to Computer Vision
number: ARTTECH-3039
description: >
  Computer vision allows machines to see and understand their environment. This
  course will equip students with the practical skills and critical theory
  needed to both employ and critically engage these techniques. Real-time body
  tracking, facial recognition and gesture analysis using RGB+D and LiDAR
  sensors, artificial intelligence and machine learning will be emphasized.
  Students will explore and critique contemporary applications ranging from
  automated mass surveillance to interactive installations. A final project will
  build on in-class workshops, technical exercises, critical readings and
  discussions.
forum: https://ats.community/c/courses/arttech-3039-spring-2018
semester: Spring
year: 2018
meetings:
  - Wednesday 9am-4pm
locations:
  - MacLean 401
sites:
  - name: General Code Discussion (Public)
    url: https://ats.community/
    comments: Post your questions in the appropriate category.
  - name: Class Website
    url: http://saic-ats.github.io/ARTTECH-3039/
  - name: Course Repository (code examples, etc)
    url: https://github.com/SAIC-ATS/ARTTECH-3039/
  - name: Course Assignments
    url: https://github.com/SAIC-ARTTECH-3039-5039
  - name: Course openFrameworks Addon
    url: https://github.com/SAIC-ATS/ofxARTTECH-3039

people:
  - name: Christopher Baker
    role: Instructor
    gravatar: 8f6ac7bc0f5c26b87269d442d5339206
    email: info@christopherbaker.net
    web: https://christopherbaker.net
    twitter: bakercp
    github: bakercp
    bio: >
      [Christopher Baker](http://christopherbaker.net) is an artist whose work
      engages the rich collection of social, technological and ideological networks
      present in the urban landscape. He creates artifacts and situations that
      reveal and generate relationships within and between these networks.
      Christopher’s work has been presented worldwide and he contributes to the open
      source community at [http://github.com/bakercp](http://github.com/bakercp).

  - name: Amay Kataria
    role: TA
    web: https://www.amaykataria.com/
    github: eulphean
    bio: >
      Amay Kataria (b. 1990) is a global artist intersecting technology with modern art mediums for self-expression. Born and brought up in Delhi, the capitol city of India, he developed artistic tendencies at the age of 14, when he started learning instruments like guitar and harmonica. After placing 1st in Future Cities India 2020 in 2007, a competition to design futuristic road architecture for Commonwealth Games held in India in 2010, his team of 4 students represented India in Washington D.C. to present their designs. During that trip, he visited U.S. universities and decided to pursue his college education abroad. At the age of 18, he moved to Virginia Tech to pursue Computer Engineering. While studying engineering, he took classes in philosophy, music appreciation, interdisciplinary product design, robotics, hardware-software, and embedded systems. After graduating from Tech in 2012, Amay joined Windows team in Microsoft as a Software Engineer in Seattle, WA.

      He explored his passion for arts through music production, attending creative writing workshops, and painting & drawing lessons in Seattle Community College and Gage Academy of Arts. In 2014, he moved to Skype4Life project in Microsoft under the mentorship of Eric Traut. During this time, he collaborated with designers, product managers, and led the development of several high-impact features for the brand new Skype app. He also participated in creative hackathons to work with modern art mediums like Augmented Reality, Artificial Intelligence, and Sound to expand his repertoire of creative mediums. Ultimately, while attending Burning Man in Nevada in 2015, when his artistic tendencies were at peak, Amay decided to pursue graduate education in fine arts. He began collating a portfolio for a MFA and left his job at Microsoft in Summer, 2017 to start school in Fall, 2017. Currently, he is pursuing a MFA in Art & Technology Studies at SAIC and is expected to graduate in 2019.



############################



baseurl: /ARTTECH-3039
url: https://saic-ats.github.io/ARTTECH-3039

timezone: America/Chicago

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

markdown: kramdown
highlighter: rouge
permalink: pretty

# jekyll-SEO
# More: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
google_site_verification: hO8fb6wgSNVw6C5qMR4ehv-IkEJwBbBguiWxmcwcVxQ

# Custom Data
google_analytics: UA-105746846-4

# Collections
collections:
  assignments:
    output: true
    name: Assignments
  notes:
    output: true
    name: Notes
  resources:
    output: true
    name: Resources
  sessions:
    output: true
    name: Sessions

  # projects:
  #   output: true
  #   name: Projects

  # Session_00:
  #   output: true
  #   name: Session 00

# Default Values
defaults:
  - scope:
      path: ""
    values:
      author: bakercp
  - scope:
      path: ""
      type: sessions
    values:
      layout: session
  - scope:
      path: ""
      type: assignments
    values:
      layout: assignment

assets:
  css:
    - name: FontAwesome
      href: https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
      # integrity: sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN
      crossorigin: anonymous

    # - name: Bootstrap
    #   href: https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css
    #   integrity: sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm
    #   crossorigin: anonymous

    - name: Bootstrap Material Design
      href: https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css
      # integrity: sha384-R80DC0KVBO4GSTw+wZ5x2zn2pu4POSErBkf8/fSFhPXHxvHJydT0CSgAP2Yo2r4I
      crossorigin: anonymous

  js:
    - name: jQuery
      src: https://code.jquery.com/jquery-3.2.1.slim.min.js
      integrity: sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN
      crossorigin: anonymous

    # - name: Popper
    #   src: https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js
    #   integrity: sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q
    #   crossorigin: anonymous

    - name: Popper
      src: https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js
      integrity: sha256-/GXjBGBWRx8/y1Be190w3hrUOFXNs9qPhthi0tbNnG8=
      crossorigin: anonymous

    - name: Bootstrap Material Design
      src: https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js
      integrity: sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9
      crossorigin: anonymous

    # - name: Bootstrap
    #   src: https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js
    #   integrity: sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl
    #   crossorigin: anonymous

    - name: Moment.js
      src: https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js
      integrity: sha256-ABVkpwb9K9PxubvRrHMkk6wmWcIHUE9eBxNZLXYQ84k=
      crossorigin: anonymous

    - name: MathJax
      src: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
      integrity: sha384-ekJxthwrl3ID8DzHP2myRUdIPhTdEgNJ1xKhDsMKDT3+kBlZ4Zwk5zH960SnLZR8
      crossorigin: anonymous
